version: 2
updates:
  - package-ecosystem: terraform
    directory: /environments/dev
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
